### ISSUE TITLE
symbol-overlay version problem

### ISSUE THREAD

**Issue by dinkonin** [kickingvegas/casual-symbol-overlay#6]
Hello
I wanted to try this package but cannot find the required dependency symbol-overlay 4.2, the linked repo https://github.com/wolray/symbol-overlay , is still at 4.1.

**Comment by kickingvegas** [comment]
@dinkonin Thanks for sharing this. The primary distribution for the Casual Packages at this time is via MELPA or MELPA Stable which will offer you the latest [4.2 version of Symbol Overlay](https://stable.melpa.org/#/symbol-overlay). My understanding is that the package manager `package.el` does not support installing specific versions and will provide you with what is actually packaged from the distribution archive.

Of note is that the `Package-Requires` header is not necessarily the source of truth here, but rather the git tag of package repo.

I will file an issue with Symbol Overlay to align the repo tag and the `PackageRequires` header. I will not back rev to 4.1 as I do not have the time and resources to QA such a change.

Discussion on package versioning can be found in this [Reddit thread](https://www.reddit.com/r/emacs/comments/etikbz/speaking_as_a_package_maintainer_please_do_not/?utm_source=reddit&utm_medium=usertext&utm_name=emacs&utm_content=t1_llimwe0).

**Comment by kickingvegas** [comment]
Link to issue request to align Package-Requires with the git tag. https://github.com/wolray/symbol-overlay/issues/113
