### ISSUE TITLE
Idea:  customize i-search behavior

### ISSUE THREAD

**Issue by rmolinari** [kickingvegas/casual-symbol-overlay#7]
Casual-symbol-overlay is great! Thanks for the work.

Is it possible to customize what  happens when I select the `I-search` option?  I use consult and would prefer to kick off a `consult-file` action.

(Maybe such behavior belongs in symbol-overlay rather than here.)

**Comment by kickingvegas** [comment]
@rmolinari Thanks for the compliment and for asking! There does not exist the ability to customize this menu. You can however copy its source (in this case `casual-symbol-overlay-tmenu`) and modify the menu to your taste. It would be best to use a different name for the prefix.

Casual Symbol Overlay is really a simple interface to Symbol Overlay which is doing all the lifting. As you suggest, I think that support for Consult is best achieved by making a [feature request for Symbol Overlay](https://github.com/wolray/symbol-overlay/issues).

**Comment by rmolinari** [comment]
For the sake of future generations, here is what I did. I didn't even have to copy-paste the definition of `casual-symbol-overlay-tmenu`. The `transient` package allow (some) modifications of existing transients.

I replaced the "I-search" suffix with my own definition.

```lisp
  (defun my/symbol-overlay-consult-line-thing-at-point ()
    "Start a consult-line search using the symbol-overlay current symbol.

If (symbol-overlay-get-symbol) is nil then do nothing.
"
    (interactive)
    (unless (minibufferp)
      (let ((symbol (symbol-overlay-get-symbol)))
        (when symbol
          (beginning-of-thing 'symbol)
          (consult-line symbol)))))

  (transient-replace-suffix 'casual-symbol-overlay-tmenu "s" '("s" "consult-line" my/symbol-overlay-consult-line-thing-at-point))

```
